[package]
name = "wuhaurou_dbs"
version = "0.1.0"
authors = ["wuhuarou <wobusbz2019@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.1.0"